/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import apoio.JComboBoxItem;
import classes.Issue;
import classes.User;
import dao.IssueDAO;
import dao.IssuePriorityDAO;
import dao.IssueStatusDAO;
import dao.IssueTypeDAO;
import dao.ProjectDAO;
import dao.UserProjectDAO;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author christian
 */
public class AtividadesNovo extends javax.swing.JPanel {

    IssueDAO issueDAO;
    IssueTypeDAO issueTypeDAO;
    IssueStatusDAO issueStatusDAO;
    IssuePriorityDAO issuePriorityDAO;
    ProjectDAO projectDAO;
    UserProjectDAO userProjectDAO;
    Color errorColor;
    Color normalColor;
    ArrayList errorsList;
    CardLayout layoutController;
    JPanel cardPanel;
    Usuarios usuarios;
    JLabel btnBack;
    JLabel lblWindow;
    User user;
    Issue issue;
    Atividades atividades;

    /**
     * Creates new form Usuario
     */
    public AtividadesNovo(JLabel btnBack, JLabel lblWindow, CardLayout lController, JPanel cardPanel, Issue issue, User user) {
        initComponents();

        // Seta o título da janela
        lblWindow.setText("NOVA ATIVIDADE");

        // Troca o action do botão "Voltar"
        btnBack.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atividades = new Atividades(btnBack, lblWindow, layoutController, cardPanel, user);
                cardPanel.add(atividades, "atividades");
                layoutController = ((CardLayout) cardPanel.getLayout());
                layoutController.show(cardPanel, "atividades");
            }
        });

        // Inicializa as variáveis de tela
        this.btnBack = btnBack;
        this.lblWindow = lblWindow;
        this.cardPanel = cardPanel;
        this.layoutController = lController;
        this.user = user;

        // Inicializa as cores;
        errorColor = new Color(255, 0, 0);
        normalColor = new Color(60, 60, 60);

        // Inicializa os DAO's
        issueDAO = new IssueDAO();
        issueTypeDAO = new IssueTypeDAO();
        issueStatusDAO = new IssueStatusDAO();
        issuePriorityDAO = new IssuePriorityDAO();
        projectDAO = new ProjectDAO();
        userProjectDAO = new UserProjectDAO();

        // Popula o combobox com os papéis
        projectDAO.lists(selProject);
        issueTypeDAO.lists(selIssueType);
        issueStatusDAO.lists(selStatus);
        issuePriorityDAO.lists(selPriority);

        // Inicia a lista de erros
        errorsList = new ArrayList();

        // Edição
        if (issue.getTitle() != null) {
            this.issue = issue;

            // Seta o título da janela
            lblWindow.setText("EDITAR ATIVIDADE");

            // Inicializa os campos
            inpTitle.setText(issue.getTitle());
            if (issue.getParentIssueId() != 0) {
                inpParentIssueId.setText(String.valueOf(issue.getParentIssueId()));
            }
            new JComboBoxItem().setSelectedItem(selProject, issue.getProjectId());
            userProjectDAO.lists(selAssignedUser, selProject.getSelectedIndex());
            new JComboBoxItem().setSelectedItem(selAssignedUser, issue.getAssignedUserId());
            new JComboBoxItem().setSelectedItem(selIssueType, issue.getIssueTypeId());
            new JComboBoxItem().setSelectedItem(selStatus, issue.getIssueStatusId());
            new JComboBoxItem().setSelectedItem(selPriority, issue.getIssuePriorityId());
            selDoneRatio.setSelectedItem(String.valueOf(issue.getDoneRatio()));
            if (issue.getEstimatedHours() != 0) {
                inpEstimatedHours.setText(String.valueOf(issue.getEstimatedHours()));
            }
            if (issue.getSpentHours() != 0) {
                inpSpentHours.setText(String.valueOf(issue.getSpentHours()));
            }
            if (issue.getDueDate() != null) {
                inpDueDate.setText(dateToString(issue.getDueDate()));
            }
            if (issue.getStartDate() != null) {
                inpStartDate.setText(dateToString(issue.getStartDate()));
            }
            if (issue.getEndDate() != null) {
                inpEndDate.setText(dateToString(issue.getEndDate()));
            }
            txtDescription.setText(issue.getDescription());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JPanel();
        inpTitle = new javax.swing.JTextField();
        sepTitle = new javax.swing.JSeparator();
        inpEstimatedHours = new javax.swing.JTextField();
        sepEstimatedHours = new javax.swing.JSeparator();
        inpParentIssueId = new javax.swing.JTextField();
        sepParentIssueId = new javax.swing.JSeparator();
        selIssueType = new javax.swing.JComboBox<>();
        inpDueDate = new javax.swing.JTextField();
        sepDueDate = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listErrors = new javax.swing.JList<>();
        selProject = new javax.swing.JComboBox<>();
        selAssignedUser = new javax.swing.JComboBox<>();
        selStatus = new javax.swing.JComboBox<>();
        selDoneRatio = new javax.swing.JComboBox<>();
        selPriority = new javax.swing.JComboBox<>();
        inpStartDate = new javax.swing.JTextField();
        sepStartDate = new javax.swing.JSeparator();
        inpEndDate = new javax.swing.JTextField();
        sepEndDate = new javax.swing.JSeparator();
        inpSpentHours = new javax.swing.JTextField();
        sepSpentHours = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(254, 254, 254));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        basePanel.setBackground(new java.awt.Color(254, 254, 254));
        basePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inpTitle.setBackground(new java.awt.Color(254, 254, 254));
        inpTitle.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        inpTitle.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpTitle.setText("Título");
        inpTitle.setBorder(null);
        inpTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inpTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpTitleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inpTitleFocusLost(evt);
            }
        });
        basePanel.add(inpTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 350, 20));

        sepTitle.setBackground(new java.awt.Color(103, 103, 103));
        sepTitle.setForeground(new java.awt.Color(29, 29, 29));
        sepTitle.setFont(new java.awt.Font("Ubuntu", 0, 3)); // NOI18N
        basePanel.add(sepTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 350, 1));

        inpEstimatedHours.setBackground(new java.awt.Color(254, 254, 254));
        inpEstimatedHours.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        inpEstimatedHours.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpEstimatedHours.setText("Horas Estimadas");
        inpEstimatedHours.setBorder(null);
        inpEstimatedHours.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inpEstimatedHours.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpEstimatedHoursFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inpEstimatedHoursFocusLost(evt);
            }
        });
        basePanel.add(inpEstimatedHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 170, 20));

        sepEstimatedHours.setBackground(new java.awt.Color(103, 103, 103));
        sepEstimatedHours.setForeground(new java.awt.Color(29, 29, 29));
        sepEstimatedHours.setFont(new java.awt.Font("Ubuntu", 0, 3)); // NOI18N
        basePanel.add(sepEstimatedHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 170, 1));

        inpParentIssueId.setBackground(new java.awt.Color(254, 254, 254));
        inpParentIssueId.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        inpParentIssueId.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpParentIssueId.setText("Tarefa Pai");
        inpParentIssueId.setBorder(null);
        inpParentIssueId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inpParentIssueId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpParentIssueIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inpParentIssueIdFocusLost(evt);
            }
        });
        basePanel.add(inpParentIssueId, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 350, 20));

        sepParentIssueId.setBackground(new java.awt.Color(103, 103, 103));
        sepParentIssueId.setForeground(new java.awt.Color(29, 29, 29));
        sepParentIssueId.setFont(new java.awt.Font("Ubuntu", 0, 3)); // NOI18N
        basePanel.add(sepParentIssueId, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 350, 1));

        selIssueType.setBackground(new java.awt.Color(254, 254, 254));
        selIssueType.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        selIssueType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Atividade" }));
        selIssueType.setToolTipText("");
        selIssueType.setOpaque(false);
        selIssueType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                selIssueTypeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                selIssueTypeFocusLost(evt);
            }
        });
        basePanel.add(selIssueType, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 170, -1));

        inpDueDate.setBackground(new java.awt.Color(254, 254, 254));
        inpDueDate.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        inpDueDate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpDueDate.setText("Data Estimada");
        inpDueDate.setBorder(null);
        inpDueDate.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inpDueDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpDueDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inpDueDateFocusLost(evt);
            }
        });
        basePanel.add(inpDueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 350, 20));

        sepDueDate.setBackground(new java.awt.Color(103, 103, 103));
        sepDueDate.setForeground(new java.awt.Color(29, 29, 29));
        sepDueDate.setFont(new java.awt.Font("Ubuntu", 0, 3)); // NOI18N
        basePanel.add(sepDueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 350, 1));

        jScrollPane1.setBorder(null);

        txtDescription.setBackground(new java.awt.Color(254, 254, 254));
        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        txtDescription.setForeground(new java.awt.Color(29, 29, 29));
        txtDescription.setRows(5);
        txtDescription.setText("Descrição");
        txtDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 29, 29)));
        txtDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescriptionFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(txtDescription);

        basePanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 730, 110));

        btnSave.setBackground(new java.awt.Color(52, 100, 127));
        btnSave.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(254, 254, 254));
        btnSave.setText("SALVAR");
        btnSave.setToolTipText("");
        btnSave.setBorderPainted(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSave.setDefaultCapable(false);
        btnSave.setName(""); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        basePanel.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 90, 40));

        jScrollPane2.setBorder(null);

        listErrors.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        listErrors.setForeground(new java.awt.Color(255, 0, 0));
        listErrors.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listErrors.setToolTipText("");
        listErrors.setFocusable(false);
        listErrors.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(listErrors);

        basePanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 640, 120));

        selProject.setBackground(new java.awt.Color(254, 254, 254));
        selProject.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        selProject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Projeto" }));
        selProject.setToolTipText("");
        selProject.setOpaque(false);
        selProject.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                selProjectFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                selProjectFocusLost(evt);
            }
        });
        basePanel.add(selProject, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 350, -1));

        selAssignedUser.setBackground(new java.awt.Color(254, 254, 254));
        selAssignedUser.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        selAssignedUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atribuído Para" }));
        selAssignedUser.setToolTipText("");
        selAssignedUser.setOpaque(false);
        selAssignedUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                selAssignedUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                selAssignedUserFocusLost(evt);
            }
        });
        basePanel.add(selAssignedUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 350, -1));

        selStatus.setBackground(new java.awt.Color(254, 254, 254));
        selStatus.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        selStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status" }));
        selStatus.setToolTipText("");
        selStatus.setOpaque(false);
        selStatus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                selStatusFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                selStatusFocusLost(evt);
            }
        });
        basePanel.add(selStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 170, -1));

        selDoneRatio.setBackground(new java.awt.Color(254, 254, 254));
        selDoneRatio.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        selDoneRatio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Concluído (%)", "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));
        selDoneRatio.setToolTipText("");
        selDoneRatio.setOpaque(false);
        selDoneRatio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                selDoneRatioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                selDoneRatioFocusLost(evt);
            }
        });
        basePanel.add(selDoneRatio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 170, -1));

        selPriority.setBackground(new java.awt.Color(254, 254, 254));
        selPriority.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        selPriority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prioridade" }));
        selPriority.setToolTipText("");
        selPriority.setOpaque(false);
        selPriority.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                selPriorityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                selPriorityFocusLost(evt);
            }
        });
        basePanel.add(selPriority, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, -1));

        inpStartDate.setBackground(new java.awt.Color(254, 254, 254));
        inpStartDate.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        inpStartDate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpStartDate.setText("Data de Início");
        inpStartDate.setBorder(null);
        inpStartDate.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inpStartDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpStartDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inpStartDateFocusLost(evt);
            }
        });
        basePanel.add(inpStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 350, 20));

        sepStartDate.setBackground(new java.awt.Color(103, 103, 103));
        sepStartDate.setForeground(new java.awt.Color(29, 29, 29));
        sepStartDate.setFont(new java.awt.Font("Ubuntu", 0, 3)); // NOI18N
        basePanel.add(sepStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 350, 1));

        inpEndDate.setBackground(new java.awt.Color(254, 254, 254));
        inpEndDate.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        inpEndDate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpEndDate.setText("Data de Conclusão");
        inpEndDate.setBorder(null);
        inpEndDate.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inpEndDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpEndDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inpEndDateFocusLost(evt);
            }
        });
        basePanel.add(inpEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 350, 20));

        sepEndDate.setBackground(new java.awt.Color(103, 103, 103));
        sepEndDate.setForeground(new java.awt.Color(29, 29, 29));
        sepEndDate.setFont(new java.awt.Font("Ubuntu", 0, 3)); // NOI18N
        basePanel.add(sepEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 350, 1));

        inpSpentHours.setBackground(new java.awt.Color(254, 254, 254));
        inpSpentHours.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        inpSpentHours.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpSpentHours.setText("Horas Gastas");
        inpSpentHours.setBorder(null);
        inpSpentHours.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inpSpentHours.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpSpentHoursFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inpSpentHoursFocusLost(evt);
            }
        });
        basePanel.add(inpSpentHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 170, 20));

        sepSpentHours.setBackground(new java.awt.Color(103, 103, 103));
        sepSpentHours.setForeground(new java.awt.Color(29, 29, 29));
        sepSpentHours.setFont(new java.awt.Font("Ubuntu", 0, 3)); // NOI18N
        basePanel.add(sepSpentHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 170, 1));

        add(basePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void inpTitleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpTitleFocusGained
        if (inpTitle.getText().trim().equals("Título")) {
            inpTitle.setText("");
            setTextFieldNormal(inpTitle, sepTitle);
        }
    }//GEN-LAST:event_inpTitleFocusGained

    private void inpTitleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpTitleFocusLost
        validateTitle();
    }//GEN-LAST:event_inpTitleFocusLost

    private void inpEstimatedHoursFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpEstimatedHoursFocusGained
        if (inpEstimatedHours.getText().trim().equals("Horas Estimadas")) {
            inpEstimatedHours.setText("");
        }
    }//GEN-LAST:event_inpEstimatedHoursFocusGained

    private void inpEstimatedHoursFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpEstimatedHoursFocusLost
        if (inpEstimatedHours.getText().trim().isEmpty()) {
            inpEstimatedHours.setText("Horas Estimadas");
        }
    }//GEN-LAST:event_inpEstimatedHoursFocusLost

    private void inpParentIssueIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpParentIssueIdFocusGained
        if (inpParentIssueId.getText().trim().equals("Tarefa Pai")) {
            inpParentIssueId.setText("");
            setTextFieldNormal(inpParentIssueId, sepParentIssueId);
        }
    }//GEN-LAST:event_inpParentIssueIdFocusGained

    private void inpParentIssueIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpParentIssueIdFocusLost
        if (inpParentIssueId.getText().trim().isEmpty()) {
            inpParentIssueId.setText("Tarefa Pai");
        }
    }//GEN-LAST:event_inpParentIssueIdFocusLost

    private void inpDueDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpDueDateFocusGained
        if (inpDueDate.getText().trim().equals("Data Estimada")) {
            inpDueDate.setText("");
            setTextFieldNormal(inpDueDate, sepDueDate);
        }
    }//GEN-LAST:event_inpDueDateFocusGained

    private void inpDueDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpDueDateFocusLost
        if (inpDueDate.getText().trim().isEmpty()) {
            inpDueDate.setText("Data Estimada");
        }
    }//GEN-LAST:event_inpDueDateFocusLost

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // Inicia a lista de erros
        errorsList = new ArrayList();

        // Cria uma lista padrão
        DefaultListModel listModel = new DefaultListModel();

        // Valida os campos
        validateTitle();
        validateAssignedUser();
        validateDoneRatio();
        validateIssueType();
        validatePriority();
        validateProject();
        validateStatus();
        validateDescription();

        if (!errorsList.isEmpty()) {
            for (int i = 0; i < errorsList.size(); i++) {
                listModel.add(i, errorsList.get(i));
            }
            listErrors.setModel(listModel);
        } else {
            Issue issue = new Issue();
            issue.setTitle(inpTitle.getText());

            if (!txtDescription.getText().trim().equals("Descrição")) {
                issue.setDescription(txtDescription.getText());
            }

            JComboBoxItem projectItem = (JComboBoxItem) selProject.getSelectedItem();
            issue.setProjectId(projectItem.getKey());
            JComboBoxItem issueTypeItem = (JComboBoxItem) selIssueType.getSelectedItem();
            issue.setIssueTypeId(issueTypeItem.getKey());
            JComboBoxItem statusItem = (JComboBoxItem) selStatus.getSelectedItem();
            issue.setIssueStatusId(statusItem.getKey());
            JComboBoxItem priorityItem = (JComboBoxItem) selPriority.getSelectedItem();
            issue.setIssuePriorityId(priorityItem.getKey());
            JComboBoxItem assignedUserItem = (JComboBoxItem) selAssignedUser.getSelectedItem();
            issue.setAssignedUserId(assignedUserItem.getKey());
            issue.setDoneRatio(Integer.valueOf(String.valueOf(selDoneRatio.getSelectedItem())));

            String strDueDate = inpDueDate.getText();
            if (!strDueDate.trim().equals("Data Estimada")) {
                issue.setDueDate(stringToDate(strDueDate));
            }

            String strStartDate = inpStartDate.getText();
            if (!strStartDate.trim().equals("Data de Início")) {
                issue.setStartDate(stringToDate(strStartDate));
            }

            String strEndDate = inpEndDate.getText();
            if (!strEndDate.trim().equals("Data de Conclusão")) {
                issue.setEndDate(stringToDate(strEndDate));
            }

            if (!inpEstimatedHours.getText().trim().equals("Horas Estimadas")) {
                issue.setEstimatedHours(Float.parseFloat(inpEstimatedHours.getText()));
            }

            if (!inpSpentHours.getText().trim().equals("Horas Gastas")) {
                issue.setSpentHours(Float.parseFloat(inpSpentHours.getText()));
            }

            if (!inpParentIssueId.getText().trim().equals("Tarefa Pai")) {
                issue.setParentIssueId(Integer.parseInt(inpParentIssueId.getText()));
            }

            if (this.issue != null) {
                issue.setId(this.issue.getId());
                issue.setUpdatedBy(this.user.getId());
                issueDAO.update(issue);
            } else {
                issue.setCreatedBy(this.user.getId());
                issue.setUpdatedBy(this.user.getId());
                issueDAO.save(issue);
            }

            atividades = new Atividades(btnBack, lblWindow, layoutController, cardPanel, user);
            cardPanel.add(atividades, "atividades");
            layoutController = ((CardLayout) cardPanel.getLayout());
            layoutController.show(cardPanel, "atividades");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtDescriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescriptionFocusGained
        if (txtDescription.getText().trim().equals("Descrição")) {
            txtDescription.setText("");
            setTextFieldNormal(inpTitle, sepTitle);
        }
    }//GEN-LAST:event_txtDescriptionFocusGained

    private void txtDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescriptionFocusLost
        validateDescription();
    }//GEN-LAST:event_txtDescriptionFocusLost

    private void selIssueTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selIssueTypeFocusGained
        selIssueType.setForeground(normalColor);
    }//GEN-LAST:event_selIssueTypeFocusGained

    private void selIssueTypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selIssueTypeFocusLost
        validateIssueType();
    }//GEN-LAST:event_selIssueTypeFocusLost

    private void selProjectFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selProjectFocusGained
        selProject.setForeground(normalColor);
    }//GEN-LAST:event_selProjectFocusGained

    private void selProjectFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selProjectFocusLost
        validateProject();
        if (selProject.getSelectedIndex() != 0) {
            userProjectDAO.lists(selAssignedUser, selProject.getSelectedIndex());
        }
    }//GEN-LAST:event_selProjectFocusLost

    private void selAssignedUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selAssignedUserFocusGained
        selAssignedUser.setForeground(normalColor);
    }//GEN-LAST:event_selAssignedUserFocusGained

    private void selAssignedUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selAssignedUserFocusLost
        validateAssignedUser();
    }//GEN-LAST:event_selAssignedUserFocusLost

    private void selStatusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selStatusFocusGained
        selStatus.setForeground(normalColor);
    }//GEN-LAST:event_selStatusFocusGained

    private void selStatusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selStatusFocusLost
        validateStatus();
    }//GEN-LAST:event_selStatusFocusLost

    private void selDoneRatioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selDoneRatioFocusGained
        selDoneRatio.setForeground(normalColor);
    }//GEN-LAST:event_selDoneRatioFocusGained

    private void selDoneRatioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selDoneRatioFocusLost
        validateDoneRatio();
    }//GEN-LAST:event_selDoneRatioFocusLost

    private void selPriorityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selPriorityFocusGained
        selPriority.setForeground(normalColor);
    }//GEN-LAST:event_selPriorityFocusGained

    private void selPriorityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selPriorityFocusLost
        validatePriority();
    }//GEN-LAST:event_selPriorityFocusLost

    private void inpStartDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpStartDateFocusGained
        if (inpStartDate.getText().trim().equals("Data de Início")) {
            inpStartDate.setText("");
        }
    }//GEN-LAST:event_inpStartDateFocusGained

    private void inpStartDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpStartDateFocusLost
        if (inpStartDate.getText().trim().isEmpty()) {
            inpStartDate.setText("Data de Início");
        }
    }//GEN-LAST:event_inpStartDateFocusLost

    private void inpEndDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpEndDateFocusGained
        if (inpEndDate.getText().trim().equals("Data de Conclusão")) {
            inpEndDate.setText("");
        }
    }//GEN-LAST:event_inpEndDateFocusGained

    private void inpEndDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpEndDateFocusLost
        if (inpEndDate.getText().trim().isEmpty()) {
            inpEndDate.setText("Data de Conclusão");
        }
    }//GEN-LAST:event_inpEndDateFocusLost

    private void inpSpentHoursFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpSpentHoursFocusGained
        if (inpSpentHours.getText().trim().equals("Horas Gastas")) {
            inpSpentHours.setText("");
        }
    }//GEN-LAST:event_inpSpentHoursFocusGained

    private void inpSpentHoursFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpSpentHoursFocusLost
        if (inpSpentHours.getText().trim().isEmpty()) {
            inpSpentHours.setText("Horas Gastas");
        }
    }//GEN-LAST:event_inpSpentHoursFocusLost

    private void setTextFieldError(JTextField textField, JSeparator separator) {
        textField.setForeground(errorColor);
        separator.setForeground(errorColor);
    }

    private void setTextFieldNormal(JTextField textField, JSeparator separator) {
        textField.setForeground(normalColor);
        separator.setForeground(normalColor);
    }

    private void validateTitle() {;
        String title = inpTitle.getText().trim();
        if (title.isEmpty() || title.equals("Título")) {
            inpTitle.setText("Título");
            setTextFieldError(inpTitle, sepTitle);
            errorsList.add("O campo \"Título\" é obrigatório!");
        }
    }

    private void validateDescription() {;
        String description = txtDescription.getText().trim();
        if (description.isEmpty() || description.equals("Descrição")) {
            txtDescription.setText("Descrição");
            txtDescription.setForeground(errorColor);
            errorsList.add("O campo \"Descrição\" é obrigatório!");
        }
    }

    private void validateIssueType() {
        int projectTypeId = selIssueType.getSelectedIndex();
        if (projectTypeId == 0) {
            selIssueType.setForeground(errorColor);
            errorsList.add("O campo \"Tipo de Atividade\" é obrigatório!");
        }
    }

    private void validateProject() {
        int projectId = selProject.getSelectedIndex();
        if (projectId == 0) {
            selProject.setForeground(errorColor);
            errorsList.add("O campo \"Projeto\" é obrigatório!");
        }
    }

    private void validateAssignedUser() {
        int assignedUserId = selAssignedUser.getSelectedIndex();
        if (assignedUserId == 0) {
            selAssignedUser.setForeground(errorColor);
            errorsList.add("O campo \"Atribuído Para\" é obrigatório!");
        }
    }

    private void validateStatus() {
        int statusId = selStatus.getSelectedIndex();
        if (statusId == 0) {
            selStatus.setForeground(errorColor);
            errorsList.add("O campo \"Status\" é obrigatório!");
        }
    }

    private void validateDoneRatio() {
        int doneRatio = selDoneRatio.getSelectedIndex();
        if (doneRatio == 0) {
            selDoneRatio.setForeground(errorColor);
            errorsList.add("O campo \"Concluído (%)\" é obrigatório!");
        }
    }

    private void validatePriority() {
        int priorityId = selPriority.getSelectedIndex();
        if (priorityId == 0) {
            selPriority.setForeground(errorColor);
            errorsList.add("O campo \"Prioridade\" é obrigatório!");
        }
    }

    private String dateToString(Date date) {
        String strDate = null;
        if (date != null) {
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            strDate = formatter.format(date);
        }
        return strDate;
    }

    private Date stringToDate(String strDate) {
        Date date = null;
        if (strDate != null && !strDate.equals("")) {
            try {
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                date = formatter.parse(strDate);
            } catch (ParseException e) {
                System.out.println(e.toString());
                e.printStackTrace();
            }
        }
        return date;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basePanel;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField inpDueDate;
    private javax.swing.JTextField inpEndDate;
    private javax.swing.JTextField inpEstimatedHours;
    private javax.swing.JTextField inpParentIssueId;
    private javax.swing.JTextField inpSpentHours;
    private javax.swing.JTextField inpStartDate;
    private javax.swing.JTextField inpTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listErrors;
    private javax.swing.JComboBox<String> selAssignedUser;
    private javax.swing.JComboBox<String> selDoneRatio;
    private javax.swing.JComboBox<String> selIssueType;
    private javax.swing.JComboBox<String> selPriority;
    private javax.swing.JComboBox<String> selProject;
    private javax.swing.JComboBox<String> selStatus;
    private javax.swing.JSeparator sepDueDate;
    private javax.swing.JSeparator sepEndDate;
    private javax.swing.JSeparator sepEstimatedHours;
    private javax.swing.JSeparator sepParentIssueId;
    private javax.swing.JSeparator sepSpentHours;
    private javax.swing.JSeparator sepStartDate;
    private javax.swing.JSeparator sepTitle;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
