/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.CardLayout;
import java.io.InputStream;

/**
 *
 * @author christian
 */
public class Main extends javax.swing.JFrame {

    CardLayout layoutController;
    Dashboard dashboard;
    Projetos projetos;
    Usuarios usuarios;
    Ajuda ajuda;
    Atividades atividades;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        dashboard = new Dashboard();
        projetos = new Projetos();
        usuarios = new Usuarios();
        ajuda = new Ajuda();
        atividades = new Atividades();

        try {
            InputStream is = GUI.class.getResourceAsStream("TestFont.ttf");
            Font font = Font.createFont(Font.TRUETYPE_FONT, is);
            return font;
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            return super.getFont();
        }

        btnDashboard.setFont("JosefinSans-Thin");

        this.setSize(1000, 500);
        cardPanel.add(dashboard, "dashboard");
        cardPanel.add(projetos, "projetos");
        cardPanel.add(usuarios, "usuarios");
        cardPanel.add(atividades, "atividades");
        cardPanel.add(ajuda, "ajuda");
        cardPanel.setSize(800, 500);

        dashboard.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btnAjuda = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnAtividades = new javax.swing.JButton();
        btnProjetos = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        exit = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(52, 100, 127));
        setForeground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardPanel.setBackground(new java.awt.Color(147, 147, 147));
        cardPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(cardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 800, 600));

        menuPanel.setBackground(new java.awt.Color(26, 50, 64));
        menuPanel.setForeground(new java.awt.Color(52, 100, 127));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAjuda.setText("AJUDA");
        btnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudaActionPerformed(evt);
            }
        });
        menuPanel.add(btnAjuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 381, 123, -1));

        btnUsuarios.setText("USUÁRIOS");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        menuPanel.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 310, 123, -1));

        btnAtividades.setText("ATIVIDADES");
        btnAtividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtividadesActionPerformed(evt);
            }
        });
        menuPanel.add(btnAtividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 227, 123, -1));

        btnProjetos.setText("PROJETOS");
        btnProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjetosActionPerformed(evt);
            }
        });
        menuPanel.add(btnProjetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 166, 123, -1));

        btnDashboard.setBackground(new java.awt.Color(153, 153, 153));
        btnDashboard.setFont(new java.awt.Font("NanumBarunGothic", 1, 14)); // NOI18N
        btnDashboard.setText("DASHBOARD");
        btnDashboard.setBorderPainted(false);
        btnDashboard.setFocusPainted(false);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        menuPanel.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 85, 123, -1));

        exit.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        exit.setForeground(new java.awt.Color(254, 254, 254));
        exit.setText("x");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        menuPanel.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jToggleButton1.setText("jToggleButton1");
        menuPanel.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        layoutController = ((CardLayout) cardPanel.getLayout());
        layoutController.show(cardPanel, "dashboard");

//        dashboard.setVisible(true);
//        projetos.setVisible(false);
//        usuarios.setVisible(false);
//        ajuda.setVisible(false);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudaActionPerformed
        layoutController = ((CardLayout) cardPanel.getLayout());
        layoutController.show(cardPanel, "ajuda");
//        dashboard.setVisible(false);
//        projetos.setVisible(false);
//        usuarios.setVisible(false);
//        ajuda.setVisible(true);
    }//GEN-LAST:event_btnAjudaActionPerformed

    private void btnProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjetosActionPerformed
        layoutController = ((CardLayout) cardPanel.getLayout());
        layoutController.show(cardPanel, "projetos");

//        dashboard.setVisible(false);
//        projetos.setVisible(true);
//        usuarios.setVisible(false);
//        ajuda.setVisible(false);
    }//GEN-LAST:event_btnProjetosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        layoutController = ((CardLayout) cardPanel.getLayout());
        layoutController.show(cardPanel, "usuarios");
//        dashboard.setVisible(false);
//        projetos.setVisible(false);
//        usuarios.setVisible(true);
//        ajuda.setVisible(false);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnAtividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtividadesActionPerformed
        layoutController = ((CardLayout) cardPanel.getLayout());
        layoutController.show(cardPanel, "atividades");
    }//GEN-LAST:event_btnAtividadesActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjuda;
    private javax.swing.JButton btnAtividades;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnProjetos;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel exit;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
