/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.CardLayout;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.ButtonGroup;

/**
 *
 * @author christian
 */
public class Main extends javax.swing.JFrame {

    CardLayout layoutController;
    Dashboard dashboard;
    Projetos projetos;
    Usuarios usuarios;
    Sobre sobre;
    Atividades atividades;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        // Faz a tela poder ser arrastada
        FrameDragListener frameDragListener = new FrameDragListener(this);
        this.addMouseListener(frameDragListener);
        this.addMouseMotionListener(frameDragListener);
        
        // Inicializa os painéis
        dashboard = new Dashboard();
        projetos = new Projetos();
        usuarios = new Usuarios();
        sobre = new Sobre();
        atividades = new Atividades();
        
        // Cria o grupo de botões do menu
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(btnDashboard);
        buttonGroup.add(btnProjetos);
        buttonGroup.add(btnAtividades);
        buttonGroup.add(btnUsuarios);
        buttonGroup.add(btnSobre);
        
        // Seta o tamanho do frame
        this.setSize(1000, 600);
        
        // Seta adiciona os painéis para troca
        cardPanel.add(dashboard, "dashboard");
        cardPanel.add(projetos, "projetos");
        cardPanel.add(usuarios, "usuarios");
        cardPanel.add(atividades, "atividades");
        cardPanel.add(sobre, "sobre");
        cardPanel.setSize(800, 500);

        dashboard.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JToggleButton();
        btnProjetos = new javax.swing.JToggleButton();
        btnSobre = new javax.swing.JToggleButton();
        btnAtividades = new javax.swing.JToggleButton();
        btnUsuarios = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(52, 100, 127));
        setForeground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardPanel.setBackground(new java.awt.Color(254, 254, 254));
        cardPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(cardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 800, 600));

        menuPanel.setBackground(new java.awt.Color(26, 50, 64));
        menuPanel.setForeground(new java.awt.Color(52, 100, 127));
        menuPanel.setMinimumSize(new java.awt.Dimension(200, 600));
        menuPanel.setPreferredSize(new java.awt.Dimension(200, 600));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDashboard.setBackground(new java.awt.Color(26, 50, 64));
        btnDashboard.setFont(new java.awt.Font("NanumGothic", 0, 18)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(254, 254, 254));
        btnDashboard.setSelected(true);
        btnDashboard.setBorder(null);
        btnDashboard.setBorderPainted(false);
        btnDashboard.setFocusable(false);
        btnDashboard.setLabel("DASHBOARD");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        menuPanel.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 60));

        btnProjetos.setBackground(new java.awt.Color(26, 50, 64));
        btnProjetos.setFont(new java.awt.Font("NanumGothic", 0, 18)); // NOI18N
        btnProjetos.setForeground(new java.awt.Color(254, 254, 254));
        btnProjetos.setText("PROJETOS");
        btnProjetos.setBorder(null);
        btnProjetos.setBorderPainted(false);
        btnProjetos.setFocusable(false);
        btnProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjetosActionPerformed(evt);
            }
        });
        menuPanel.add(btnProjetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, 60));

        btnSobre.setBackground(new java.awt.Color(26, 50, 64));
        btnSobre.setFont(new java.awt.Font("NanumGothic", 0, 18)); // NOI18N
        btnSobre.setForeground(new java.awt.Color(254, 254, 254));
        btnSobre.setText("SOBRE");
        btnSobre.setBorder(null);
        btnSobre.setBorderPainted(false);
        btnSobre.setFocusable(false);
        btnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreActionPerformed(evt);
            }
        });
        menuPanel.add(btnSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 200, 60));

        btnAtividades.setBackground(new java.awt.Color(26, 50, 64));
        btnAtividades.setFont(new java.awt.Font("NanumGothic", 0, 18)); // NOI18N
        btnAtividades.setForeground(new java.awt.Color(254, 254, 254));
        btnAtividades.setText("ATIVIDADES");
        btnAtividades.setBorder(null);
        btnAtividades.setBorderPainted(false);
        btnAtividades.setFocusable(false);
        btnAtividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtividadesActionPerformed(evt);
            }
        });
        menuPanel.add(btnAtividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 60));

        btnUsuarios.setBackground(new java.awt.Color(26, 50, 64));
        btnUsuarios.setFont(new java.awt.Font("NanumGothic", 0, 18)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(254, 254, 254));
        btnUsuarios.setText("USUÁRIOS");
        btnUsuarios.setBorder(null);
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setFocusable(false);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        menuPanel.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 200, 60));

        getContentPane().add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        layoutController = ((CardLayout) cardPanel.getLayout());
        layoutController.show(cardPanel, "dashboard");
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjetosActionPerformed
        layoutController = ((CardLayout) cardPanel.getLayout());
        layoutController.show(cardPanel, "projetos");
    }//GEN-LAST:event_btnProjetosActionPerformed

    private void btnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreActionPerformed
        layoutController = ((CardLayout) cardPanel.getLayout());
        layoutController.show(cardPanel, "sobre");
    }//GEN-LAST:event_btnSobreActionPerformed

    private void btnAtividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtividadesActionPerformed
        layoutController = ((CardLayout) cardPanel.getLayout());
        layoutController.show(cardPanel, "atividades");
    }//GEN-LAST:event_btnAtividadesActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        layoutController = ((CardLayout) cardPanel.getLayout());
        layoutController.show(cardPanel, "usuarios");
    }//GEN-LAST:event_btnUsuariosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAtividades;
    private javax.swing.JToggleButton btnDashboard;
    private javax.swing.JToggleButton btnProjetos;
    private javax.swing.JToggleButton btnSobre;
    private javax.swing.JToggleButton btnUsuarios;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
