/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author christian
 */
public class ProjetosNovo extends javax.swing.JPanel {

    /**
     * Creates new form ProjetosListagem
     */
    public ProjetosNovo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inpNome = new javax.swing.JTextField();
        sepNome = new javax.swing.JSeparator();
        inpSobrenome = new javax.swing.JTextField();
        sepSobrenome = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(254, 254, 254));
        setPreferredSize(new java.awt.Dimension(800, 540));

        inpNome.setBackground(new java.awt.Color(254, 254, 254));
        inpNome.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        inpNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inpNome.setText("Usuário");
        inpNome.setBorder(null);
        inpNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inpNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inpNomeFocusLost(evt);
            }
        });
        inpNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpNomeActionPerformed(evt);
            }
        });

        sepNome.setBackground(new java.awt.Color(103, 103, 103));
        sepNome.setForeground(new java.awt.Color(29, 29, 29));
        sepNome.setFont(new java.awt.Font("Ubuntu", 0, 3)); // NOI18N

        inpSobrenome.setBackground(new java.awt.Color(254, 254, 254));
        inpSobrenome.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        inpSobrenome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inpSobrenome.setText("Usuário");
        inpSobrenome.setBorder(null);
        inpSobrenome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inpSobrenome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpSobrenomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inpSobrenomeFocusLost(evt);
            }
        });
        inpSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpSobrenomeActionPerformed(evt);
            }
        });

        sepSobrenome.setBackground(new java.awt.Color(103, 103, 103));
        sepSobrenome.setForeground(new java.awt.Color(29, 29, 29));
        sepSobrenome.setFont(new java.awt.Font("Ubuntu", 0, 3)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inpSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sepSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inpNome, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sepNome, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(418, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(inpNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sepNome, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inpSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sepSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inpNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpNomeFocusGained
        if (inpNome.getText().trim().equals("Usuário")) {
            inpNome.setText("");
        }
    }//GEN-LAST:event_inpNomeFocusGained

    private void inpNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpNomeFocusLost
        if (inpNome.getText().trim().isEmpty()) {
            inpNome.setText("Usuário");
        }
    }//GEN-LAST:event_inpNomeFocusLost

    private void inpNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpNomeActionPerformed

    private void inpSobrenomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpSobrenomeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_inpSobrenomeFocusGained

    private void inpSobrenomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpSobrenomeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_inpSobrenomeFocusLost

    private void inpSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpSobrenomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inpNome;
    private javax.swing.JTextField inpSobrenome;
    private javax.swing.JSeparator sepNome;
    private javax.swing.JSeparator sepSobrenome;
    // End of variables declaration//GEN-END:variables
}
