/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author christian
 */
public class ProjetosNovo extends javax.swing.JPanel {

    /**
     * Creates new form ProjetosListagem
     */
    public ProjetosNovo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inpTitle = new javax.swing.JTextField();
        sepTitle = new javax.swing.JSeparator();
        selProjectType = new javax.swing.JComboBox<>();
        selManager = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        lblImagemUsuario = new javax.swing.JLabel();
        lblProjetos = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JLabel();
        lblNomeUsuario = new javax.swing.JLabel();
        btnSalvarProjeto = new javax.swing.JButton();

        setBackground(new java.awt.Color(254, 254, 254));
        setPreferredSize(new java.awt.Dimension(800, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inpTitle.setBackground(new java.awt.Color(254, 254, 254));
        inpTitle.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        inpTitle.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inpTitle.setText("Título");
        inpTitle.setBorder(null);
        inpTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inpTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpTitleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inpTitleFocusLost(evt);
            }
        });
        inpTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpTitleActionPerformed(evt);
            }
        });
        jPanel1.add(inpTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 730, 20));

        sepTitle.setBackground(new java.awt.Color(103, 103, 103));
        sepTitle.setForeground(new java.awt.Color(29, 29, 29));
        sepTitle.setFont(new java.awt.Font("Ubuntu", 0, 3)); // NOI18N
        jPanel1.add(sepTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 730, 1));

        selProjectType.setBackground(new java.awt.Color(254, 254, 254));
        selProjectType.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        selProjectType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Projeto" }));
        selProjectType.setToolTipText("");
        selProjectType.setBorder(null);
        selProjectType.setOpaque(false);
        selProjectType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selProjectTypeActionPerformed(evt);
            }
        });
        jPanel1.add(selProjectType, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 730, -1));

        selManager.setBackground(new java.awt.Color(254, 254, 254));
        selManager.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        selManager.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente" }));
        selManager.setToolTipText("");
        selManager.setBorder(null);
        selManager.setOpaque(false);
        jPanel1.add(selManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 730, -1));

        txtDescription.setBackground(new java.awt.Color(254, 254, 254));
        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txtDescription.setRows(5);
        txtDescription.setText("Descrição");
        txtDescription.setBorder(null);
        jScrollPane1.setViewportView(txtDescription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 730, 136));

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setFont(new java.awt.Font("Ubuntu Light", 0, 30)); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        btnExit.setText("x");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        jPanel3.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, -1, -1));

        lblImagemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        jPanel3.add(lblImagemUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        lblProjetos.setFont(new java.awt.Font("NanumGothic", 0, 24)); // NOI18N
        lblProjetos.setText("NOVO PROJETO");
        jPanel3.add(lblProjetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        jPanel3.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblNomeUsuario.setFont(new java.awt.Font("NanumGothic", 0, 18)); // NOI18N
        lblNomeUsuario.setText("Christian Bayer");
        jPanel3.add(lblNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 35, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 90));

        btnSalvarProjeto.setBackground(new java.awt.Color(52, 100, 127));
        btnSalvarProjeto.setFont(new java.awt.Font("NanumGothic", 0, 14)); // NOI18N
        btnSalvarProjeto.setForeground(new java.awt.Color(254, 254, 254));
        btnSalvarProjeto.setText("SALVAR");
        btnSalvarProjeto.setToolTipText("");
        btnSalvarProjeto.setBorderPainted(false);
        btnSalvarProjeto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalvarProjeto.setDefaultCapable(false);
        btnSalvarProjeto.setName(""); // NOI18N
        btnSalvarProjeto.setOpaque(true);
        btnSalvarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProjetoActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvarProjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 90, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void inpTitleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpTitleFocusGained
        if (inpTitle.getText().trim().equals("Usuário")) {
            inpTitle.setText("");
        }
    }//GEN-LAST:event_inpTitleFocusGained

    private void inpTitleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpTitleFocusLost
        if (inpTitle.getText().trim().isEmpty()) {
            inpTitle.setText("Usuário");
        }
    }//GEN-LAST:event_inpTitleFocusLost

    private void inpTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpTitleActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void selProjectTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selProjectTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selProjectTypeActionPerformed

    private void btnSalvarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarProjetoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExit;
    private javax.swing.JButton btnSalvarProjeto;
    private javax.swing.JLabel btnVoltar;
    private javax.swing.JTextField inpTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagemUsuario;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblProjetos;
    private javax.swing.JComboBox<String> selManager;
    private javax.swing.JComboBox<String> selProjectType;
    private javax.swing.JSeparator sepTitle;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
